import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const time = new Date();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="header-top">
            <div className="container flex justify-between margin-left-right items-center h-full">
              <div className="header-top__time">
                {`0${time.getMonth()}-${time.getDate()} ${time.getHours()}:${time.getMinutes()}`}
              </div>
              <div className="header-top__right flex">
                <div className="header-top__right__register">
                  Đăng ký
                  <span>+</span>
                </div>
                <div className="header-top__right__login">Đăng nhập</div>
              </div>
            </div>
          </div>
          <div className="header-bottom ">
            <div className="container flex margin-left-right items-center justify-between uppercase font-medium text-black">
              <Link href={"/"}>
                <img className="" src="/logo.png" />
              </Link>
              <div className="header-bottom__item">
                <h3>KU siêu hot</h3>
              </div>
              <div className="header-bottom__item">
                <h3>THể thao</h3>
              </div>
              <div className="header-bottom__item">
                <h3>Live casino</h3>
              </div>
              <div className="header-bottom__item">
                <h3>games</h3>
              </div>
              <div className="header-bottom__item">
                <h3>Xổ số</h3>
              </div>
              <div className="header-bottom__item">
                <h3>e-sport</h3>
              </div>
              <div className="header-bottom__item">
                <h3>bắn cá</h3>
              </div>
              <div className="header-bottom__item">
                <h3>đối kháng</h3>
              </div>
              <div className="header-bottom__item">
                <h3>Ưu đãi</h3>
              </div>
            </div>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
